name: Testing with devbox

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: true
          devbox-version: 0.13.7

      - name: Create pdfs
        run: devbox run make all

      - uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: '*.pdf'
